name: Enviro+ Python Library Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Python ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip setuptools tox pytest pytest-cov

      - name: Run Tests
        run: |
          tox -e py

      - name: Coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 -m pip3 install coveralls
          coveralls --service=github
